FROM php:7.1-apache
	
	RUN pecl install xdebug-2.5.5 \
		&& docker-php-ext-enable xdebug
	RUN a2enmod rewrite
	RUN docker-php-ext-install pdo pdo_mysql mbstring
	RUN apt-get update && \
        apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && \
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
        docker-php-ext-install gd
    RUN cp /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/
	RUN a2enmod ssl
