FROM php:7.4-apache

# Install and configure Xdebug
RUN pecl install xdebug-3.1.3 \
	&& docker-php-ext-enable xdebug \
	&& echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_host=docker.for.mac.localhost" >> /usr/local/etc/php/conf.d/xdebug.ini

# Enable Apache's mod_rewrite
RUN a2enmod rewrite

# Update Linux package DB
RUN apt-get update

# Install PHP extensions: pdo, pdo_mysql, mbstring
RUN apt-get install -y libonig-dev \
	&& docker-php-ext-install pdo pdo_mysql mbstring

# Install PHP extensions: gd
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
	&& docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
	&& docker-php-ext-install gd

# Install PHP extensions: zip
RUN apt-get install -y \
		libzip-dev \
		zip \
	&& docker-php-ext-configure zip \
	&& docker-php-ext-install zip

# Enable SSL in Apache
RUN cp /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/
RUN a2enmod ssl

