<?php

namespace OHM\tickets;

class CreateTicketResult
{
    private bool $created = false;// True if a ticket was created.
    private array $errors = []; // Errors during ticket creation.
    private ?array $apiResponse = null; // The raw API response.
    private ?int $apiStatusCode = null; // The HTTP status code for the API request.

    // A UUID generated by OHM to reference errors encountered
    // during the API request for ticket creation.
    private ?string $ohmErrorId = null;

    // The support ticket service may or may not provide this after ticket creation.
    private ?string $ticketId = null;

    /*
     * created
     */

    public function isCreated(): bool
    {
        return $this->created;
    }

    public function setCreated(bool $created): CreateTicketResult
    {
        $this->created = $created;
        return $this;
    }

    /*
     * errors
     */

    public function getErrors(): array
    {
        return $this->errors;
    }

    public function setErrors(array $errors): CreateTicketResult
    {
        $this->errors = $errors;
        return $this;
    }

    public function addError(string $error): CreateTicketResult
    {
        $this->errors[] = $error;
        return $this;
    }

    /*
     * apiResponse
     */

    public function getApiResponse(): ?array
    {
        return $this->apiResponse;
    }

    public function setApiResponse(array $apiResponse): CreateTicketResult
    {
        $this->apiResponse = $apiResponse;
        return $this;
    }

    /*
     * apiStatusCode
     */

    public function getApiStatusCode(): ?int
    {
        return $this->apiStatusCode;
    }

    public function setApiStatusCode(int $apiStatusCode): CreateTicketResult
    {
        $this->apiStatusCode = $apiStatusCode;
        return $this;
    }

    /*
     * ohmErrorId
     */

    public function getOhmErrorId(): ?string
    {
        return $this->ohmErrorId;
    }

    public function setOhmErrorId(string $ohmErrorId): CreateTicketResult
    {
        $this->ohmErrorId = $ohmErrorId;
        return $this;
    }

    /*
     * ticketId
     */

    public function getTicketId(): ?string
    {
        return $this->ticketId;
    }

    public function setTicketId(?string $ticketId): CreateTicketResult
    {
        $this->ticketId = $ticketId;
        return $this;
    }


}