FROM php:8.1-apache

ARG enabledev

# Install and configure Xdebug
RUN if [ "ztrue" = "z$enabledev" ]; then \
		pecl install xdebug-3.3.1 \
		&& docker-php-ext-enable xdebug \
		&& echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
		&& echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
		&& echo "xdebug.client_host=docker.for.mac.localhost" >> /usr/local/etc/php/conf.d/xdebug.ini \
		&& echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/xdebug.ini \
		; \
	fi

# Enable Apache's mod_rewrite
RUN a2enmod rewrite

# Update Linux package DB
RUN apt-get update \
	&& apt-get install -y vim less

# Install PHP extensions: pdo, pdo_mysql, mbstring, gettext
RUN apt-get install -y libonig-dev \
	&& docker-php-ext-install pdo pdo_mysql mbstring gettext

# Install PHP extensions: gd
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
	&& docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
	&& docker-php-ext-install gd

# Install PHP extensions: zip
RUN apt-get install -y \
		libzip-dev \
		zip \
	&& docker-php-ext-configure zip \
	&& docker-php-ext-install zip

# Enable SSL in Apache
RUN if [ "ztrue" = "z$enabledev" ]; then \
		cp /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/ \
		&& a2enmod ssl \
		; \
	fi

# Enable error logging
RUN if [ "ztrue" = "z$enabledev" ]; then \
		cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
		; \
	else \
		cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
		; \
	fi

# Set SSL certificate location
RUN if [ "ztrue" = "z$enabledev" ]; then \
		sed -i -e 's|SSLCertificateFile.*/etc/ssl/certs/ssl-cert-snakeoil.pem|SSLCertificateFile      /etc/ssl/docker/lumenlearning.crt|' /etc/apache2/sites-enabled/default-ssl.conf \
		&& sed -i -e 's|SSLCertificateKeyFile.*/etc/ssl/private/ssl-cert-snakeoil.key|SSLCertificateKeyFile /etc/ssl/docker/lumenlearning.key|' /etc/apache2/sites-enabled/default-ssl.conf \
		; \
	fi

